### ISSUE TITLE
Stock_predicter.ipynb: definition of y in 212

### ISSUE THREAD

**Issue by Ovi65** [abr-98/Stock_prediction_hybrid_model#1]
Thanks for your project. 

In line 212 in `Stock_predicter.ipynb` you split the data: `X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)`

How have you defined y in this statement? 

Thank you

**Comment by abr-98** [comment]
y is y_df_mod.Values. y_df_mod is declared in lines 204 205.

 I think it was somehow replaced during uploads by mistake.

Thank you for pointing out.
